blank_issues_enabled: false
contact_links:
  - name: Support
    url: https://github.com/marc2825/Blender_SmartClip/discussions
    about: For usage questions or if you are unsure whether something is a bug, please ask here.
