blank_issues_enabled: false
contact_links:
  - name: Support
    url: https://github.com/marc2825/Blender_SmartClip.git
    about: If Discussions is enabled, replace this URL with your repo discussions page.
